frase = input('Digite algo:')
print('O tipo primitivo desse valor é:',type(frase))
print('Só tem espaços?', frase.isspace())
print('É um numero?', frase.isnumeric())
print('É alfabético?', frase.isalpha())
print('É alfanumérico?', frase.isalnum())
print('Está em letras maiúsculas?', frase.isupper())
print('Está em letras minúsculas?', frase.islower())
print('Está capitalizada?', frase.istitle())